### ISSUE TITLE
Find and replace fonts

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#122]
Try to find a font that matches Invision a little more closely.

**Comment by briaguya** [comment]
https://projects.invisionapp.com/share/NHFQ3V1673T#/screens/277649911
https://projects.invisionapp.com/share/G2FQ413S6WK#/screens/277024879
https://docs.google.com/presentation/d/1KP_nktKkgS3DKINtBM4990E3qWdeU-fwypf7ltYkH-A/edit#slide=id.g2f0dc9c6e1_0_147

**Comment by luqmaan** [comment]
https://fonts.google.com/specimen/Source+Sans+Pro?query=source+sans+pro&selection.family=Source+Sans+Pro

**Comment by luqmaan** [comment]
Before:

![image](https://user-images.githubusercontent.com/1275831/36506433-406abdc0-171c-11e8-8dd7-fb3613f99adb.png)

After

![image](https://user-images.githubusercontent.com/1275831/36506435-42ac85e6-171c-11e8-8b33-a1bb3fb59308.png)
