### ISSUE TITLE
Replace status icons

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/ctxfloods#123]
The invision icons look different/better so let's make/use them.

https://projects.invisionapp.com/share/NHFQ3V1673T#/screens/277649911
https://projects.invisionapp.com/share/G2FQ413S6WK#/screens/277024879
https://docs.google.com/presentation/d/1KP_nktKkgS3DKINtBM4990E3qWdeU-fwypf7ltYkH-A/edit#slide=id.g2f0dc9c6e1_0_147

**Comment by ohsk** [comment]
@briaguya @luqmaan I just exported a set of status icon files, available here:
https://www.dropbox.com/sh/9f6y5lilzfehcva/AABcud1bO8apPuFIcsFpDaFga?dl=0

What's the best process to share files with y'all? Dropbox? I could publish them to a [gist like this](https://gist.github.com/ohsk/e01de7e9c792e6b346eaeaede9fb2edf)? Or I could submit a PR to update assets? Let me know whatever is easiest for you.

A few notes:

### SVG sizing
The original svgs all had `width="42px" height="48px" viewBox="0 0 42 48"`. The versions I just created are all sized to fit just the markers, with no additional "padding" built into the asset itself. Let me know if you'd like me to adjust them to be closer to the way the original svgs were sized.

### Status icons
I'm not sure if you're using CSS to style svg icons directly, so I made two sets of status icon svgs (all with no exported background color, even though it's shown below).
 
![image](https://user-images.githubusercontent.com/1689222/36946884-1f1902ca-1f92-11e8-83ac-75c5e9f74d23.png)

This way there's a grey icon version for the non-selected statuses, like this:
![image](https://user-images.githubusercontent.com/1689222/36946908-5b79a580-1f92-11e8-9b1d-bb588c9c1924.png)

**Comment by luqmaan** [comment]
Dropbox seems fine, but whatever is easiest for you works for me. Fancy gist tho.

**Comment by luqmaan** [comment]
✅ 

![image](https://user-images.githubusercontent.com/1275831/38205805-be15e75e-365c-11e8-98f8-77b276e45c57.png)
![image](https://user-images.githubusercontent.com/1275831/38205812-c50d4b2e-365c-11e8-8b27-77347d89c3b0.png)
