### ISSUE TITLE
Replace Google geocoder

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#148]
We used the Mapbox geocoder and didn't like it. So we tried the Google geocoder. Unfortunately, it seems like Google only allows you to use it on Google Maps.

So we need to find another geocoder.

- Here
  - https://developer.here.com/plans
  - Free 15k transactions (requests) per month / ~500/day
  - $49 / 100k / month
  - $119 / 250K
  - $449 / 1M
  - $1 for each extra 2,000
- Google
  - https://developers.google.com/maps/pricing-and-plans/
  - Free up to 2,500 requests per day.
  - $0.50 USD / 1,000 additional requests, up to 100,000 daily, if billing is enabled.
  - You must conspicuously display the "powered by Google" attribution (and any other attribution(s) required by Google in the Maps APIs Documentation) on or adjacent to the relevant Service search box and Google search results. If you use the standard Google search control, or the standard Google search control form, this attribution will be included automatically, and you must not modify or obscure this automatically-generated attribution.
  - No modification of search results. You will not modify, reorder, augment, or manipulate search results in any way unless you explicitly notify the end user of your actions.
- Mapbox
  - https://www.mapbox.com/geocoding/#pricing
  - Free up to 50,000 geocode requests/mo
  - Then $0.50 per 1,000 geocode requests
- Esri
  - If you don't need to store the results of a geocode request, you can make 1,000,000 (one million) requests per month included with your free ArcGIS Developer subscription. 
- [geocode.earth](https://geocode.earth/) (by Mapzen)
- [Nominatim](http://nominatim.openstreetmap.org/)
- [OpenCage Data](https://geocoder.opencagedata.com/)
- [OSMNames](https://osmnames.org/)

**Comment by briaguya** [comment]
Using Here now.
