### ISSUE TITLE
Ongoing closure notification

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#168]
Admins w/ ongoing closures receive email alerts after __ [amt of time]

- Need to ask how this should behave

**Comment by luqmaan** [comment]
https://serverless.com/framework/docs/providers/aws/events/schedule/

**Comment by briaguya** [comment]
* Make sure we are keeping track of what notifications have already been sent
  * This will help us avoid sending too many emails
* Figure out how to make this work as a lambda function
  * Either directly query using postgres on backend or figure out how to hit graphQL
* Possible future improvement: configuration for timing

**Comment by atx-adam** [comment]
24 hours after a closure: send an email to prompt an admin to check/open

**Comment by Niicck** [comment]
Resolved by https://github.com/cityofaustin/ctxfloods/pull/405
