### ISSUE TITLE
Add Lat/Long to Crossings

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/ctxfloods#17]
Using PostGIS (Postgres Extension) we need to add location data to the Crossings table in our postgres schema (schema.sql), as well as update the data (data.sql) to give crossings geolocations.

Then we'll need to test it out a bit:
Any test that reads from the crossings table (ctrl-f allCrossings) it should get location data
Any test that writes to the crossings table it should set location data

We should not be able to create crossings without location data.

Update any frontend components that are reading from crossings to also have lat/long data.

**Comment by mateoclarke** [comment]
Working on this now.

1st merged & squashed PR: https://github.com/cityofaustin/ctxfloods/commit/4179db4e8ebc08e44fe009b2c5e8eda977c2849d

Current WIP PR: https://github.com/cityofaustin/ctxfloods/pull/19

**Comment by mateoclarke** [comment]
Last PR: https://github.com/cityofaustin/ctxfloods/pull/21
