### ISSUE TITLE
Users List Page

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#172]
- [ ] Invision screens
  - Do we already have these?
- [ ] Update design to match Invision
- [ ] Features
  - [ ] Add a way to filter by jurisdiction
  - [ ] Archive user
  - [ ] Add user(s) to community

* Ask @ohsk if he would like to design a screen for this
* Filter by jurisdiction
  * Just need to add a control for this for super admins
* Archive user:
  * Just need a button and maybe a confirm dialog
  * Already have deactivateUser and reactivateUser on backend
* Edit community
  * Follow pattern of edit crossing page, but only allow super admin to change.
* Add user
  * Community admins can add to their community
  * Super admins can add to any communitiy
  * Non-admins can't add users

**Comment by briaguya** [comment]
* Ask @ohsk if he would like to design a screen for this
* Filter by jurisdiction
  * Just need to add a control for this for super admins
* Archive user:
  * Just need a button and maybe a confirm dialog
  * Already have deactivateUser and reactivateUser on backend
* Edit community
  * Follow pattern of edit crossing page, but only allow super admin to change.
* Add user
  * Community admins can add to their community
  * Super admins can add to any communitiy
  * Non-admins can't add users

**Comment by briaguya** [comment]
using this as a reference for the add user page:
https://projects.invisionapp.com/share/PHBVXJ8FD#/screens/248177171

**Comment by luqmaan** [comment]
@ohsk Let us know if you have any ideas on the user list page.

**Comment by ohsk** [comment]
@luqmaan @briaguya sorry for the delay on my end! Looks like you got the page stood up via https://github.com/cityofaustin/ctxfloods/pull/226. Let me know if you need a specific eye on anything for that page.

Just a heads up — the terms of my design contract were to tackle mocks for the [10 key screens](https://github.com/cityofaustin/ctxfloods/issues/135#issue-300363675) outlined by UX and sticker sheets for UI components that can be used for other screens without fully-fledged mocks. I'll circle back on email about what else y'all might need.

**Comment by luqmaan** [comment]
![image](https://user-images.githubusercontent.com/1275831/43099534-14b0bc32-8e88-11e8-9322-b4751c2d45e6.png)
