### ISSUE TITLE
Reset/Forgot password flow

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#177]
- [ ] Invision screens
- [ ] Add to backend
- [ ] Build components

🎷:
- [x] Create reset password page
  - [x] Password/Confirm fields
  - [x] Submit button
- [x] Create forgot password page
  - [x] email field
  - [x] "Email Sent!"
  - [x] emailSentSuccessfully in state
- [x] Create Postgres role for reset emailer
- [x] Create Postgres role for password resetter
- [ ] Create Postgres Function to generate JWT for resetting (generate_password_reset_jwt)
  - [ ] Only the reset emailer should have access to this
  - [ ] Takes in an email address to get the user id
  - [ ] Should create a JWT with the user id and the password resetter role
- [x] Update backend server to serve multiple endpoints (part of #191)
- [x] Create new endpoint (sendResetPasswordEmail)
  - [x] Call generate_password_reset_jwt
  - [ ] Generate email and send email with JWT and link to reset password page
  - [x] Return success/error
- [x] Update forgot password page
  - [x] Call sendResetPasswordEmail
  - [x] On success set emailSentSuccessfully
- [x] Create Postgres function to reset passwords (reset_password)
  - [x] only the password resetter role should have access to this
  - [x] takes in a new password
  - [x] gets the user id from the JWT
  - [x] updates user with new password
  - [x] Returns success/failure
- [x] Update reset password page
  - [x] Get JWT from email link
  - [x] Call resetPassword using GraphQL
  - [x] On success log in
  - [ ] On failure display error and allow retry (invalid (too long/short pw etc.))
    - [ ] Add some client side verification, try turning it off and submitting
- [ ] Update User page
  - [ ] For admins, add link to send reset password email to each user

**Comment by briaguya** [comment]
resolved by #205
