### ISSUE TITLE
Add creeks/streams layer from watershed department

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#180]
There are a lot of bodies of water missing from the map.

Can we add the watershed departments creeks layer to the map?

**Comment by ohsk** [comment]
@luqmaan I can add these to the basemap if we have the source data

**Comment by luqmaan** [comment]
👍 I'll let you know when we get the source data from watershed.

**Comment by atx-adam** [comment]
from watershed
[FEMA_Creeks_Centerlines.zip](https://github.com/cityofaustin/ctxfloods/files/1807856/FEMA_Creeks_Centerlines.zip)

**Comment by ohsk** [comment]
@luqmaan just tried out the `FEMA_Creeks_Centerlines` layer in Mapbox. You can [check it out here](https://api.mapbox.com/styles/v1/croweatx/cjewwe6h90lzn2rqjkwekiosl.html?fresh=true&title=true&access_token=pk.eyJ1IjoiY3Jvd2VhdHgiLCJhIjoiY2o1NDFvYmxkMHhkcDMycDF2a3pseDFpZiJ9.UcnizcFDleMpv5Vbv8Rngw#12.8/30.265179/-97.742830/0).

I few thoughts: 
* Unfortunately, I don't think there's a "width" attribute on the layer, so I can't really articulate variances in creek width. Not a huge deal, but just wanted to mention this.
* This water layer is pretty detailed; should we limit it's visibility to only lower zoom levels? Right now it appears at >z11 in the test map I made.

**Comment by luqmaan** [comment]
Thanks for trying it out!

We're currently not using styles or tiles from Mapbox studio. Which means that if we want to show the creeks layer we'd probably need to send the 30MB shape file. I tried simplifying it with http://mapshaper.org/ and could get the size down to 20MB with topojson or 2MB with SVG and 100% simplification. 2MB is still too large.

On the other hand, Mapbox studio has some really fancy processing and compression. Loading the map @ohsk setup with the creek layers stays is pretty lightweight:

![image](https://user-images.githubusercontent.com/1275831/37618458-523bb3a2-2b84-11e8-8364-639b6559bf4c.png)

So, I think we should switch to using the Mapbox tiles if we're going to use the creek layer. We need to figure out how much this will cost us in practice. To answer this, we need access to the atxfloods.com Google Analytics account #203.

**Comment by ohsk** [comment]
@luqmaan glad to hear the tiles were a helpful new approach!
Think we need any styling modifications to the creeks layer before closing this ticket?

**Comment by luqmaan** [comment]
I think the only change we'll need is to filter out Mapbox's streams and creeks. I'll make that change.

Btw, I've been using the file `ctxfloods-dark-MAR22-luq`.

**Comment by luqmaan** [comment]
✅ 

![image](https://user-images.githubusercontent.com/1275831/38206015-a4e4c236-365d-11e8-9d43-245da14f8b97.png)
