### ISSUE TITLE
Check that our map styles aren't hiding streams

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#182]
There are a lot of small bodies of water missing from the map. We should check our map styles to make sure we're not hiding streams, etc.

**Comment by ohsk** [comment]
@luqmaan I can look into this if we have examples of the bodies of water that we should be looking for

**Comment by luqmaan** [comment]
Looks like were filtering out some water stuff. Fixed it in https://github.com/cityofaustin/ctxfloods/pull/189.

![image](https://user-images.githubusercontent.com/1275831/37231414-bfd63814-23b0-11e8-931a-5df46868fae6.png)

![image](https://user-images.githubusercontent.com/1275831/37231421-c7140264-23b0-11e8-907e-54ba359a4727.png)
