### ISSUE TITLE
View photos for crossings that have wildlife cams

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#195]
- [ ] Questions
  - [ ] Does this go in a tooltip? Or does it go in the crossing sidebar?
  - [ ] Do admins need to be able to edit this?
    - Watershed plans to add "two dozen" more cameras this year
  - [ ] How does this relate to the ATD/traffic cameras? #185 
  - [ ] Do we need a camera icon on the map where cameras are? Currently cameras are associated with crossings. Do they have to be associated with crossings?
- [ ] Invision screens
- [ ] Add to backend
- [ ] Add to frontend

**Comment by wilhitem** [comment]
need to know all the different camera types and how to interface with them. Once we have that, we can estimate how long depending on whether they have an API/etc.
