### ISSUE TITLE
Invalid tokens cause auth issues

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/ctxfloods#210]
Right now if a user has an invalid JWT token in localstorage they will be unable to log in at all. This generally happens when we've deployed with a different JWT secret from the previous deploy.

the current workaround is to run:
`localStorage.setItem('jwt_user_token', null)`

Since rotating keys is generally a good thing we should account for this scenario and wipe the token if it's invalid (unless we find a better way to handle this)

**Comment by Niicck** [comment]
Resolved with https://github.com/cityofaustin/ctxfloods/issues/379
