### ISSUE TITLE
Test and update responsiveness on mobile

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#235]
- [ ] Dashboard
  - [ ] Crossing list
  - [ ] Crossing map
  - [ ] Add crossing
  - [ ] Crossing detail
  - [ ] History
  - [ ] Manage users
- [ ] Public
  - [ ] Crossing map
  - [ ] Flood safety
  - [ ] Open data
  - [ ] About

Todos

- [ ] Hit area for geolocate buttons are tiny
- [ ] Pinching on safari zooms out of page, reproduceable on iPhone SE

**Comment by ohsk** [comment]
@luqmaan took a bit more of a look on mobile, starting with the Dashboard view. Here are a few of my notes / thoughts:

## 1. Navigation
Two UX options come to mind. Not sure what the team's general philosophy is over there WRT mobile navs.

Horizontal scrolling nav | Dropdown nav
------------ | -------------
![image](https://user-images.githubusercontent.com/1689222/38779580-6828e08a-4098-11e8-9144-d2b143988640.png) | ![image](https://user-images.githubusercontent.com/1689222/38779578-627e6bc8-4098-11e8-8301-050c4aa6c01a.png)

## 2. Logo
Perhaps consider scaling down the logo on small screens to maybe 24-32px tall, to save precious vertical space.

Current | Proposed
--- | ---
![image](https://user-images.githubusercontent.com/1689222/38779637-23b2d6e4-4099-11e8-837b-af0a032d8505.png) | ![image](https://user-images.githubusercontent.com/1689222/38779645-3296c0e4-4099-11e8-8c3f-8d693d30170d.png)


## 3. Crossing List toggles
Consider keeping "Last updated" toggle on the right side to maintain consistency and association with the dates, which are on the right-hand side of each crossing card.

Current | Proposed
--- | ---
![image](https://user-images.githubusercontent.com/1689222/38779617-ce247688-4098-11e8-91f4-613f44e4464a.png) | ![image](https://user-images.githubusercontent.com/1689222/38779608-bb331796-4098-11e8-981c-dc6c7b1ffdbd.png)

**Comment by luqmaan** [comment]
- Navigation
  - 👍 for dropdown nav over horizontal scrolling nav
  - The only confusing thing might be the communities dropdown we added in https://github.com/cityofaustin/ctxfloods/pull/242
- Logo
  - 👍 for reducing the size
  - Could we also hide the "Dashboard" text on mobile?
- Crossing List toggles
  - 👍 for swapping them

**Comment by ohsk** [comment]
@luqmaan do you think it'd be unreasonable to remove both Logo and Dashboard on mobile? Real estate is really tight when also trying to accommodate a community dropdown that's somewhat separate from the nav dropdown... 

Logo + Nav | Community selector + Nav
--- | ---
![image](https://user-images.githubusercontent.com/1689222/38997643-f0bb6d8e-43bb-11e8-84cb-5869e84679b0.png) | ![image](https://user-images.githubusercontent.com/1689222/38997579-cc548d0e-43bb-11e8-8394-654b54306c8d.png)

**Comment by luqmaan** [comment]
I think the logo is important so that users know what site they're on. They may have been linked to the site instead of typing in the URL. It's also important for branding.

Since I'm in a time crunch, I'm using horizontal scrolling for the menu on mobile. I'll let you know when its published so you can try it out @ohsk.

![image](https://user-images.githubusercontent.com/1275831/39156514-1b646050-471c-11e8-8d16-6d2ca0206b2b.png)

**Comment by luqmaan** [comment]
Could we get rid of the "Search for a place, community, or crossing" text?

What purpose does it serve?

It seems like it doesn't really explain to the user they can search very well, given the low contrast issue: https://github.com/cityofaustin/ctxfloods/issues/252.

**Comment by luqmaan** [comment]
We conducted a lot of this testing in April.
