### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#241]
We need a favicon.

**Comment by ohsk** [comment]
@luqmaan @benguhin 
let me know what you think of this for the favicon:

![favicon-228](https://user-images.githubusercontent.com/1689222/38992138-cc53695a-43ad-11e8-9a4d-4711ea42c783.png)

Exports in standard sizes here:
https://www.dropbox.com/sh/n9e4u8vsogzi748/AAB9zJXH66nunjHSflXpfOZta?dl=0

**Comment by luqmaan** [comment]
Looks great.

**Comment by luqmaan** [comment]
![image](https://user-images.githubusercontent.com/1275831/39156983-361042a0-471e-11e8-970e-3748edd8b8ec.png)

**Comment by benguhin** [comment]
👍
