### ISSUE TITLE
Gzip graphql responses

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#243]
The responses from the /graphql endpoint are not gzipped.

This is important to fix before we launch, since the query to fetch open crossings is huge:

```js
// open crossings with community ids
Content-Length: 442704
// open crossings with community ids, community { id, name }
Content-Length: 695389
```

![image](https://user-images.githubusercontent.com/1275831/38744968-dc496a48-3f08-11e8-9423-b1c0849a03b0.png)

**Comment by luqmaan** [comment]
Maybe https://www.npmjs.com/package/serverless-content-encoding https://github.com/xeno-dohai/serverless-content-encoding

**Comment by briaguya** [comment]
Made a branch to test it: http://ctxfloods-frontend-test-gzip.s3-website-us-east-1.amazonaws.com/map

Map load on master:
![image](https://user-images.githubusercontent.com/6384156/38756770-3a3a14dc-3f30-11e8-9749-ab14c448602f.png)

On gzipped branch:
![image](https://user-images.githubusercontent.com/6384156/38756797-4ed80d90-3f30-11e8-95ce-ed18e4e2e94a.png)

**Comment by briaguya** [comment]
fixed on backend https://github.com/cityofaustin/ctxfloods-backend/pull/7
