### ISSUE TITLE
Search UX

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#246]
The search bar did not work well in user testing. https://github.com/cityofaustin/ctxfloods/issues/222

- The search bar doesn't work
  - There is no obvious primary action
  - Can't use enter/go on Desktop
  - The search bar doesn't look active on mobile when clicked
  - Searching for addresses did not work
  - The quality of the geocoder is important
    - We can't use the Google geocoder/places API with Mapbox
  - Users don't understand what the suggested search items are

**Comment by wilhitem** [comment]
closing for now as issues have been addressed, waiting for next round of testing for new feedback on search.
