### ISSUE TITLE
Search input is low contrast

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#252]
Some feedback we got when evaluating the design of CTXfloods is that the search input is low contrast. It's not immediately apparent that the search input is something you can click on.

![image](https://user-images.githubusercontent.com/1275831/39142027-1dd78420-46ef-11e8-84ac-2d572958cce3.png)

**Comment by luqmaan** [comment]
One way we can add contrast is to make the search input's background white:

![image](https://user-images.githubusercontent.com/1275831/39142177-7e9eb814-46ef-11e8-9f5f-156f4811663c.png)

What do you think @ohsk?

**Comment by ohsk** [comment]
I agree, making the background white helps! My other suggestion for making it feel more clickable is making the search box inset, like this:

![image](https://user-images.githubusercontent.com/1689222/39186754-76c7298c-4799-11e8-9a68-1665d4497232.png)

Perhaps even with rounded corners like the other input components:

![image](https://user-images.githubusercontent.com/1689222/39186876-c694eed6-4799-11e8-89b9-8c46973f566a.png)

**Comment by briaguya** [comment]
Addressed in #270
