### ISSUE TITLE
Users confused by crossing detail on mobile

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#278]
Users are confused when they click on a marker on mobile and the map disappears.
- [ ] Don't hide search
- [ ] Implement details in tool tip

**Comment by luqmaan** [comment]
We fixed this in https://github.com/cityofaustin/ctxfloods/pull/272.

**Comment by luqmaan** [comment]
Two improvements:

- [ ] The map jumps when the search bar hides. Animate it or don't hide the search bar when you expand a tooltip.
- [ ] Move the details view into the tooltip

![image](https://user-images.githubusercontent.com/1275831/43097877-16891b62-8e83-11e8-80a5-12d165094d55.png)

**Comment by briaguya** [comment]
<img width="1126" alt="screen shot 2018-07-23 at 2 23 43 pm" src="https://user-images.githubusercontent.com/6384156/43098226-1a8af536-8e84-11e8-9589-fcf572eeeb33.png">

**Comment by toribr** [comment]
![screen shot 2018-07-25 at 4 55 18 pm](https://user-images.githubusercontent.com/3790067/43229781-992b1fd0-902b-11e8-8ca8-c5cc595441a6.png)

Proposed mobile mockup of expanded detail view. To close, user would simply click away.
