### ISSUE TITLE
Zooming on mobile is buggy

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#281]
Pinching on mobile made the page zoom in, which made it difficult to zoom into the map. https://github.com/cityofaustin/ctxfloods/issues/222
* mobile safari on 10 and 12 (10.3.3 last update for the Iphone 5, everything newer is on 12)
* mobile chrome usage (32% on android 8, 22% on 7, 16% on 6, 11% ob 7.1, 8% on 5.1, 3% on 8.1, 2% on 5, >1% on 4) 
Browser stack can be used for testing mobile devices

- [ ] test in mobile safari on 10 and 12 
- [ ] test in mobile chrome

**Comment by briaguya** [comment]
The deployed version seems to still have the issue, I'll keep investigating

**Comment by briaguya** [comment]
I've done quite a bit of testing of this on Mobile Safari, Mobile Chrome, and Samsung Internet. I haven't been able to reproduce it. Unless someone else finds it I'll consider it done.
