### ISSUE TITLE
Zoom behavior when selecting crossings

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/ctxfloods#299]
We have currently removed any zooming when selecting a crossing. This is a great thing for when we're tapping on the map because random zooms get confusing, however, we set this zoom on flyto based on the behavior we wanted when someone selects a crossing from the search.

There are currently three ways to select a crossing:
* Click/tap the map
* Use the search bar
* Use the nearby crossings

In each scenario we should understand from a design stand point what behavior we're looking for.
We have a few options here:
* Never zoom, always show tooltip
* Zoom on search only, don't zoom on nearby or map tap
* Other?

**Comment by toribr** [comment]
I don't understand this comment - I see gobs of zooming on every type of  selection.

However, it seems like it would make sense to zoom on nearby or search. But when the crossing is already in view on the map, zooming makes less sense as it may relocate the viewer on the map unnecessarily.
