### ISSUE TITLE
Contributor - add crossing and history menu items give 'unauthorized' message

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/ctxfloods#375]
Problem: As a contributor, if i click on the 'add crossing' or 'history' navigation links in the top menu, i get a blank page with the text 'not authorized' present but barely noticeable.

If they aren't allowed to access those items, can we remove them? 

Steps to recreate:
1. log in as a contributor
2. click on add crossing or history

expected results:
the pages display

actual results:
User receives a 'not authorized' message
![screen shot 2018-10-29 at 1 42 20 pm](https://user-images.githubusercontent.com/1779067/47672730-b728c780-db80-11e8-93c5-9fa1d2b630ea.png)

**Comment by wilhitem** [comment]
Based on conversation with Watershed today, the history list should be filtered by jurisdiction

**Comment by Niicck** [comment]
Resolved by https://github.com/cityofaustin/ctxfloods/pull/412
