### ISSUE TITLE
crossing history filtered by admin jurisdiction

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/ctxfloods#382]
Problem: If i log in as an admin for a specific jurisdiction, my history tab isn't filtering down to just my jurisdiction.

steps to recreate:
* Log in as a super user
* change the status for an existing crossing in community A (city of austin)
* Log out
* log in as an admin for a different community (city of leander)
* click on history in top level navigation

Expected result:
History is limited to changes in your community

Actual result:
History for all points displayed

**Comment by Niicck** [comment]
CrossingStatusHistoryPage => 
CrossingStatusHistory =>
InfiniteCrossingStatusHistoryPaginationContainer =>
InfiniteCrossingStatusHistoryList =>

CrossingMapSidebar =>
InfiniteCrossingStatusHistoryPaginationContainer => ...

CrossingStatusHistoryPage has unused statusHistoryQuery
