### ISSUE TITLE
new user password reset process

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/ctxfloods#386]
Problem: Right now when we create new users they receive the same process as a user for reset password. The link expires in 30 minutes and as new users may not be expecting that, we want a different workflow.

1. Create new user
2. Email sent to new user:
"Welcome [First name] [Last name] to [url]! 

Please click here to start the password reset process."
3. Link in email leads to https://floodstest.austintexas.io/dashboard/forgot_password
4. User enters email....basically follow the forgot password process from there.

**Comment by Niicck** [comment]
For now, I set the jwt expiration to 30 days instead of 30 minutes. This is just for the sake of watershed testing usability, I'll implement a better process in the future.
