### ISSUE TITLE
User emails case sensitive

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/ctxfloods#389]
Problem: It appears that the email address field is case sensitive. Jorge put together that pattern when attempting to reset his password.

Steps to recreate:
1. Create a user with upper case letters (Marni.Wilhite@austintexas.gov)
2. Go to https://floodstest.austintexas.io/dashboard/forgot_password
3. enter the email address with all lower case letters (marni.wilhite@austintexas.gov)
4. Click send

Expected result:
email is case insensitive (I assume this is standard now) and identifies the correct email and successfully send the password reset email to Marni.Wilhite@austintexas.gov

Actual result:
System displays the "Failed to send password reset email" error message.

**Comment by Niicck** [comment]
Emails are no longer case sensitive, add will be recognized no matter what case users enter them in.
