### ISSUE TITLE
Change timezone to Central

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/ctxfloods#437]
Since we are currently based in texas, lets change the timezone from UTC to Central. :)

You can see the screenshot below where i just changed the time of the crossing @8:46 according to my laptop set to central standard and the crossing history which instead shows 2:46.

We should also update the data downloads to export the time at CDT as well.
![screen shot 2019-01-14 at 8 47 38 am](https://user-images.githubusercontent.com/1779067/51119813-6a48aa80-17d9-11e9-92ee-7a621203af37.png)

**Comment by Niicck** [comment]
Related to https://github.com/cityofaustin/ctxfloods/issues/413
