### ISSUE TITLE
autofill on add new user issues with next button

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/ctxfloods#441]
Problem:
I have been unable to recreate but i wanted to report and see if you can investigate

Jorge reported that when he went to the add new user page, when autofill was used it prevented the next button from being activated. He said this was on Windows w/ Chrome.

I have tried several times and had no issues. Can you try and close out if you can't recreate?

Steps to recreate:
* Ensure autofill settings are set up in your browser
* log into floodstest.austintexas.io/dashboard
* Click on manage users
* Click on add new users
** Autofill settings display contact info
* Next button issues present according to Jorge.

This could have been in an old version and maybe that is why i can't recreate...

**Comment by Niicck** [comment]
I can replicate this bug on my computer. I think it depends on the version of Chrome that you're running.

I'm going to try disabling autocomplete for this form. It would only ever be used for test accounts anyway.
