### ISSUE TITLE
CSS Architecture & Naming Improvements

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/ctxfloods#59]
Two ideas came up.

1.  Use a utility that constructs our classnames using BEM. We want to improve on what we've started doing here: https://github.com/cityofaustin/ctxfloods/pull/55/files#diff-355af4b3ffde5653df5792bb227b1f44L18
2. Namespace all CSS with `.floods` at the app level?

Here is an example of one approach to naming classes that we kinda like.
https://design.cms.gov/guidelines/code-conventions/

**Comment by luqmaan** [comment]
👍 I'll start renaming things to follow https://design.cms.gov/guidelines/code-conventions/.

![image](https://user-images.githubusercontent.com/1275831/37295987-a67514b0-25e7-11e8-81dc-e0f907e569e8.png)
