### ISSUE TITLE
Refactor save crossing update mutation refetch

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/ctxfloods#62]
@ifsimicoded questioned the performance of this refetch of the full list of crossings. When @briaguya tested it with many crossings, it was noticeably slower. We should dig deeper into how this query can be optimized, if Apollo has some suggested patterns, do we need to adopt pagination as a strategy to deal with this?

Google: "Apollo optimistic UI"
https://dev-blog.apollodata.com/tutorial-graphql-mutations-optimistic-ui-and-store-updates-f7b6b66bf0e2

**Comment by mateoclarke** [comment]
https://github.com/cityofaustin/ctxfloods/pull/56#discussion-diff-145512933R40

**Comment by briaguya** [comment]
resolved with #68
