### ISSUE TITLE
Implement "glob importing" for Sass with webpack.

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/ctxfloods#70]
Right now, we have to maintain a manifest of utility class imports manually.

https://github.com/cityofaustin/ctxfloods/blob/22c1d4864824f078e02c6730e02f0ff97818f062/frontend/src/index.scss#L1-L4

There is a better way...
https://stackoverflow.com/questions/43283447/import-all-sass-file-within-directory-with-webpack

**Comment by luqmaan** [comment]
I'd prefer to have explicit imports.
