### ISSUE TITLE
Minimize SVGs

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/ctxfloods#91]
We need to audit our use of SVGs and make sure they are all minimized.

For example, this PR adds a bunch of svg icons we should minify.
https://github.com/cityofaustin/ctxfloods/pull/90

**Comment by alexpriceco** [comment]
@mateoclarke, it looks like many of these were exported with Sketch. This PR would be a spot easier if we had that source file—any idea where it is?
Also, safe to assume that all SVGs to minify are located [here](https://github.com/cityofaustin/ctxfloods/tree/master/frontend/src/images)?

**Comment by mateoclarke** [comment]
Hey @alexpriceco, when we talked about this IRL last night I thought you were talking about Budget Party. Sorry for the confusion.

Here is a link to the Sketch file. This should be the most recently updated but let me know if something looks off: https://drive.google.com/open?id=1EwutsoqZRIYoIlebVCxO0KeDX0tQb1zI

Yes, all SVGs should be in that folder. But also for bonus points, we are using a react font awesome in some places. Any file that has `import FontAwesome from 'react-fontawesome';` is using it. It would be nice if were more consistent about using svgs for all icons.

**Comment by luqmaan** [comment]
Will come back to this later. A bunch of the SVGs are changing.
